title:              Clean Blog TEST
email:              dst05054@naver.com
description:        A Blog Theme TEST
author:             TAEMIN KIM
baseurl:            "/temmmin-blog-test"
url:                "https://temmmin.github.io"

# Social Profiles
twitter_username:   none
github_username:    none
facebook_username:  none
instagram_username: tem_minn_ 
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
